Версия проекта с использованием бд для хранения данных
helloWoor1d/java-filmorate pull request #8
Opened 2024-04-24 15:09 UTC by helloWoor1d

2024-04-24 19:22 UTC, andrew-larkin requested changes
Привет! Очень хорошо получилось реализовать новый функционал! Остается внести небольшие правки по коду, связанные с архитектурой, (обрати внимание, что я написал комменты по одному разу, но они актуальны для всех подобных случаев) и работа будет принята.

2024-04-24 19:22 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/dto/FilmDTO.java
> +    private Mpa mpa;
если речь идет о dto, то мы не можем использовать у него внутри объекты моделей, которые представляют собой таблицы базы данных - это плохая практика с точки зрения безопасности. поэтому вместо Mpa, Genre стоит использовать либо их id, либо их собственные dto

2024-04-24 19:22 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/model/Genre.java
> +@Data
в аннотации @Data уже содержатся аннотации @Getter и @Setter. но тут есть другой момент: @Data некорректно рассчитывает хэш объекта, что может стать проблемой при ее использовании в классах-моделях. поэтому тут лучше оставить просто @Getter и @Setter, а также можно добавить другие необходимые аннотации

2024-04-24 19:22 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>      private final LikeStorage likeStorage;
внедрение "чужих" репозиториев/storage в сервис не очень хорошая практика - здесь происходит нарушение иерархии. Если нам требуются другие объекты из БД, то более правильнее будет внедрять в сервис другие сервисы

2024-04-24 20:26 UTC, helloWoor1d commented on src/main/java/ru/yandex/practicum/filmorate/service/film/FilmService.java
>      private final LikeStorage likeStorage;
на счет использования UserDbStorage в классе FilmService поняла, сменила на UserService. А вот LikeDbStorage и FriendDbStorage я считала как относящиеся к FilmService/UserService и поэтому для них нет отдельных сервисов. Стоит добавить и поменять?

2024-04-25 16:07 UTC, andrew-larkin approved these changes
Привет! Отлично, работа принята! LikeDbStorage и FriendDbStorage для них нет отдельных сервисов - поэтому их внедрение в соответствующие сервисы это ок.

2024-04-26 20:55 UTC, merged